# Service for function: ConfigResetEncOffset
# Request: function input parameters
uint8 obj_type
uint8 axis_mask

---

# Response: execution result
int32 result  # 0 for success, others for error code
