# Service for function: FbkRegisterUserDataSet
# Request: function input parameters
string name
int32 data_type
int32 sub
int32 data_num

---

# Response: execution result
int32 result  # 0 for success, others for error code
