# StateSwitchToPD.srv - Switch to PD control mode
# Corresponds to FX_L1_State_SwitchToPDMode

# Request
uint8 obj_type               # Object type (FXObjType)
uint32 timeout               # Timeout in milliseconds
float64 vel_ratio            # Velocity scaling ratio
float64 acc_ratio            # Acceleration scaling ratio
float64[7] k                 # PD proportional gains (stiffness)
float64[7] d                 # PD derivative gains (damping)

---

# Response
int32 result                 # Defined in FXFuncReturn
