# Service for function: SystemSendFile
# Request: function input parameters
string local_file_path
string remote_file_path

---

# Response: execution result
int32 result  # 0 for success, others for error code